use_default_settings: true
general:
  debug: false
  instance_name: "Anvesha AI Search Node"

search:
  formats:
    - html
    - json
  safe_search: 0
  autocomplete: "duckduckgo"
  default_region: "in-en"

server:
  secret_key: "anvesha_secret_key_12345"

outgoing:
  request_timeout: 10.0
